FROM docker.m.daocloud.io/library/golang:alpine AS builder
WORKDIR /app
ADD . /app
RUN cd /app \
    && sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories \
    && apk update && apk add --no-cache nodejs npm \
    && npm i package.json \
    && go env -w GOPROXY=https://goproxy.cn,direct \
    && go mod tidy\
    && go build -o  mage mage.go
#    && npm config set registry https://registry.npm.taobao.org \
    && npm install \
